### ISSUE TITLE
webkit-gtk fails to build

### ISSUE THREAD

**Issue by mgiritli** [hhfeuer/Gentoo-Gnome-3.30-X#12]
Hi,

I am unable to completely upgrade to 3.30 due to an compile error on webkit-gtk-2.22.2. Any ideas? I couldn't find any similar issues...

The only info is the final line about python3 not supported by 2.7 I have python 3.6,3.5,3.4 and 2.7 installed.

[1574/2931] cd /mtmp/portage/net-libs/webkit-gtk-2.22.2/work/webkit-gtk-2.22.2_build/Source/WebCore && gdbus-codegen --interface-prefix org.freedesktop.GeoClue2. --c-namespace Geoclue --generate-c-code /mtmp/portage/net-libs/webkit-gtk-2.22.2/work/webkit-gtk-2.22.2_build/DerivedSources/WebCore/Geoclue2Interface /usr/share/dbus-1/interfaces/org.freedesktop.GeoClue2.xml
FAILED: DerivedSources/WebCore/Geoclue2Interface.c DerivedSources/WebCore/Geoclue2Interface.h 
cd /mtmp/portage/net-libs/webkit-gtk-2.22.2/work/webkit-gtk-2.22.2_build/Source/WebCore && gdbus-codegen --interface-prefix org.freedesktop.GeoClue2. --c-namespace Geoclue --generate-c-code /mtmp/portage/net-libs/webkit-gtk-2.22.2/work/webkit-gtk-2.22.2_build/DerivedSources/WebCore/Geoclue2Interface /usr/share/dbus-1/interfaces/org.freedesktop.GeoClue2.xml
: python_wrapper_setup: python3 is not supported by python2.7 (PYTHON_COMPAT)

**Comment by hhfeuer** [comment]
webkit-gtk has still only PYTHON_COMPAT=( python2_7 ) set and uses gdbus-codegen which is currently installed in a python3 version only.  I'll come up with a fix.

**Comment by hhfeuer** [comment]
Yes, sorry.
I've pushed new -r1 ebuilds for glib, glib-utils and gdbus-codegen now but the upgrade process is rather ugly. Due to file collisions, you'll have to
emerge -C glib gdbus-codegen glib-utils
and then re-emerge those packages
emerge -C glib gdbus-codegen glib-utils
After that, webkit-gtk builds fine.

**Comment by mgiritli** [comment]
ok many thanks, will try

**Comment by mgiritli** [comment]
Just to confirm, it compiled fine at the end. Thank you very much.
