### ISSUE TITLE
not finding glib when compiling harfbuzz

### ISSUE THREAD

**Issue by mgiritli** [hhfeuer/Gentoo-Gnome-3.30-X#15]
I encountered a new problem I believe which affects the compiling of harfbuzz-2.0.2, required by chromium. It simply can not find glib and it breaks down during configuration:

checking for GLIB... no
configure: error: glib support requested but glib-2.0 not found

**Comment by hhfeuer** [comment]
Building fine here, 1.9.0 and 2.0.2 tested.
Please post the output of
emerge -pv glib harfbuzz

**Comment by hhfeuer** [comment]
Is there a config.log created you could attach?

**Comment by mgiritli** [comment]
[config.log](https://github.com/hhfeuer/Gentoo-Gnome-3.30-X/files/2613462/config.log)

**Comment by mgiritli** [comment]
I hope it helps

**Comment by hhfeuer** [comment]
Ok, looks odd.
Please check if the files
/usr/lib64/pkgconfig/glib-2.0.pc
/usr/lib32/pkgconfig/glib-2.0.pc
exist and are not empty.
If missing, please re-emerge glib and check if the files appear.

**Comment by hhfeuer** [comment]
When correctly installed,
pkg-config  --modversion glib-2.0
should output
2.58.1

**Comment by mgiritli** [comment]
Neither of them is empty:

/usr/lib64/pkgconfig/glib-2.0.pc:

prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib64
includedir=${prefix}/include

bindir=${exec_prefix}/bin
glib_genmarshal=${bindir}/glib-genmarshal
gobject_query=${bindir}/gobject-query
glib_mkenums=${bindir}/glib-mkenums

Name: GLib
Description: C Utility Library
Version: 2.58.1
Requires.private: libpcre
Libs: -L${libdir} -lglib-2.0
Libs.private: -pthread  -lpcre
Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include


/usr/lib32/pkgconfig/glib-2.0.pc:

prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib32
includedir=${prefix}/include

bindir=${exec_prefix}/bin
glib_genmarshal=${bindir}/glib-genmarshal
gobject_query=${bindir}/gobject-query
glib_mkenums=${bindir}/glib-mkenums

Name: GLib
Description: C Utility Library
Version: 2.58.1
Requires.private: libpcre
Libs: -L${libdir} -lglib-2.0
Libs.private: -pthread  -lpcre
Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include

Also, pkg-config --modversion glib-2.0 returns 2.58.1

**Comment by hhfeuer** [comment]
Looking again at the config.log it seems that no lib at all is found using pkg-config, glib is just the first to be reported, so i rather suspect that the $PKG_CONFIG variable in the configure script is somehow either unset or incorrectly set, so pkg-config itself is not found. Looks more like a general issue with the build environment. Don't know if
PKG_CONFIG=/usr/bin/pkg-config emerge -1 harfbuzz
would be a temporary workaround. 
/usr/bin/pkg-config belongs to
[ebuild   R    ] dev-util/pkgconfig-0.29.2::gentoo  USE="-hardened -internal-glib" ABI_X86="32 (64) (-x32)" 1.970 KiB

**Comment by mgiritli** [comment]
Interesting emerging pkgconfig solved it. I have no idea what was wrong....But many thanks for the tip.
