### ISSUE TITLE
please remove x11-wm/mutter

### ISSUE THREAD

**Issue by aspann** [hhfeuer/Gentoo-Gnome-3.30-X#23]
Hey,

finally the gentoo-portage is updating to gnome 3.30, wich means right now there is a merge conflict with mutter. See:

```
  (x11-wm/mutter-3.30.2:0/0::Gnome-3-30-X, ebuild scheduled for merge) conflicts with
    >=x11-wm/mutter-3.30.1:0/3[introspection] required by (gnome-base/gnome-shell-3.30.2-r1:0/0::gentoo, installed)
```

This could be fixed by simply remove the ebuild for mutter from the repo.

cheers.

**Comment by hhfeuer** [comment]
I've been watching this since gnome 3.30 hit the official gentoo tree a month ago and some 3.32 ebuilds were added. Isn't this only a problem if using ~amd64? In that case this overlay would be obsolete and should be disabled anyway or is official portage missing ebuilds this overlay has?

**Comment by aspann** [comment]
Ah, totally overseen this.. Yes should only be a problem on a ~amd64. 

Sorry, that was my fault.

**Comment by aspann** [comment]
using ~amd64 makes this repo obsolete. Still waiting for the 3.32.X :)

closed.
