### ISSUE TITLE
dev-lang/vala-0.40.9 - missing dependency

### ISSUE THREAD

**Issue by aspann** [hhfeuer/Gentoo-Gnome-3.30-X#4]
Hi,

please add (R)DEPEND on "media-gfx/graphviz" to vala, otherwise it will fail to compile.

```
checking for LIBGVC... no
configure: error: Package requirements (libgvc >= 2.16) were not met:

No package 'libgvc' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```

**Comment by aoterolorenzo** [comment]
Same problem here, installing vala-bootstrap with jhbuild bootstrap vala-bootstrap in macos Mojavechecking for LIBGVC... no
configure: error: Package requirements (libgvc >= 2.16) were not met:

No package 'libgvc' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBGVC_CFLAGS
and LIBGVC_LIBS to avoid the need to call pkg-config.

**Comment by aspann** [comment]
I'm not a OSX specialist, but you sould install "graphviz" before compiling vala. That should fix that issue.

**Comment by aspann** [comment]
Is there a reason for not using brew to install vala on OSX? 

Nevertheless, I think your issue is vala specific and should be tracked/solved by the vala community, you find their issue-tracker here: https://gitlab.gnome.org/GNOME/vala/issues

**Comment by hhfeuer** [comment]
media-gfx/graphviz dependency added.
