### ISSUE TITLE
app-arch/file-roller-3.30.0 - meson build issue

### ISSUE THREAD

**Issue by aspann** [hhfeuer/Gentoo-Gnome-3.30-X#5]
Hi,
please see: https://github.com/mesonbuild/meson/issues/4257

There is an issue on the meson generate. Its on the roadmap for meson-0.48.1.

temporary fix for this is:
`emerge -1 =dev-util/meson-0.47.1 && emerge -1 =app-arch/file-roller-3.30.0`

**Comment by hhfeuer** [comment]
Added a dependency to file-roller-3.30.1 to block the broken meson version.
