### ISSUE TITLE
Gnome 3.30.1 and future 3.30.2 point release

### ISSUE THREAD

**Issue by enx1998** [hhfeuer/Gentoo-Gnome-3.30-X#6]
Hi,
I would like to know if you think to update ebuilds to 3.30.1 (already released) and 3.30.2 (near future) realeases.
This would be great because of many bugfixes made by gnome team.

Thanks Vincenzo

**Comment by hhfeuer** [comment]
This will happen.
Motivation was just low after finishing the 3.30.0 release to look at that code again;)

**Comment by enx1998** [comment]
Hi hhfeuer,
thanks for your reply, I really appreciated your work with all your gnome repositories.
I think that, if will, you can skip the first point release and concentrate your work on 3.30.2 when it will be released.
Thanks again for your work, you gave me the opportunity to try latest release of gnome with my stable installation.

Bye Vincenzo

**Comment by hhfeuer** [comment]
3.30.2 is now online
