### ISSUE TITLE
dev-libs/glib-2.58.1: gnome-meson.eclass could not be found by inherit()

### ISSUE THREAD

**Issue by enx1998** [hhfeuer/Gentoo-Gnome-3.30-X#8]
dev-libs/glib-2.58.1 ebuild give me this error:

> * ERROR: dev-libs/glib-2.58.1::Gnome-3-30-X failed (depend phase):
> *   gnome-meson.eclass could not be found by inherit()
> * 
> * Call stack:
> | *            ebuild.sh, line 635:  Called source '/var/lib/layman/Gnome-3-30-X/dev-libs/glib/glib-2.58.1.ebuild'
> *   glib-2.58.1.ebuild, line  13:  Called inherit 'bash-completion-r1' 'epunt-cxx' 'flag-o-matic' 'gnome-meson' 'libtool' 'linux-info' 'multilib' 'multilib-minimal' 'pax-utils' 'python-r1' 'toolchain-funcs' 'versionator' 'virtualx'
> *            ebuild.sh, line 300:  Called die
> * The specific snippet of code:
> *   		[[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
> * 
> * If you need support, post the output of `emerge --info '=dev-libs/glib-2.58.1::Gnome-3-30-X'`,
> * the complete build log and the output of `emerge -pqv '=dev-libs/glib-2.58.1::Gnome-3-30-X'`.
> * Working directory: '/usr/lib64/python3.6/site-packages'

![image](https://user-images.githubusercontent.com/20546217/48648102-6e7d6500-e9ee-11e8-8b2b-65280c68ba41.png)

I'm doing something wrong?

Thanks ENx

**Comment by enx1998** [comment]
I think this package has some more issues because after changing gnome-meson with meson eclass I'm having errors merging it: 

> git-r3_src_unpack: command not found

and after adding git-r3 eclass I have this error:

> No URI provided and EGIT_REPO_URI unset

Thanks Vincenzo

**Comment by hhfeuer** [comment]
Should be fixed now, please resync and check.

**Comment by enx1998** [comment]
Hi hhfeuer,
now this message appears:

> \>\>\> Verifying ebuild manifests
!!! A file is not listed in the Manifest: '/var/lib/layman/Gnome-3-30-X/dev-libs/glib/files/glib-2.50.0-external-gdbus-codegen.patch'

**Comment by hhfeuer** [comment]
Sorry, forgot to clean up. Is removed now.

**Comment by enx1998** [comment]
Ok, now it emerges without problems, thanks a lot for your work.
